## Introduction to Calendar spread strategy

A calendar spread is an options strategy that involves buying and selling options with the same strike price but different expiration dates. Specifically, a long calendar spread is established by buying a longer-term option and selling a shorter-term one. This strategy benefits from the difference in time decay (theta) between the two options, with the short-term option's value eroding faster, especially if the underlying asset's price stays near the strike price.

One of the main advantages of a long calendar spread is its defined risk profile: the maximum loss is limited to the initial net debit (the upfront cost of opening the position). This makes the strategy more capital efficient compared to purchasing only a long-term option.

From a margin perspective, calendar spreads offer favorable treatment. The long option acts as a hedge against the short option, reducing the broker's required margin compared to holding a naked short position. The margin requirement is usually tied to the initial cost of the spread.

Additionally, there is assignment risk for the short-term option as it nears expiration, especially if it moves in-the-money. However, the long-term option provides a layer of protection, as it can offset the obligations resulting from the assignment.

In summary, long calendar spreads are a risk-defined, capital-efficient strategy that offers reduced margin requirements compared to uncovered short positions, while still allowing for profits if the underlying asset's price remains near the strike as the short option expires.

## Data Retrieval

After describing the Calendar spread strategy, let's now see how we can leverage our tool to implement it. The first step is the retrieval of the data with our requests. We will implement the strategy on the “OESX” product.

First, let's fetch the series for OESX. We will make two requests, one for short-term options with expiration date less than 30 days, and another one for long-term options with expiration date of more than 30 days. For this filtering, we will use option `max_tte` and `min_tte`, which filter the returned series by expiration date.
Calendar spread needs the exercise price (strike price) to be the same, so we will filter it by the same value. 
We will also need to generate the template for the processing for our estimator endpoint, so that the margins can be calculated.

In [3]:
!margin_estimator_tool get_series \
    --version LIVE \
    --products OESX \
    --max_tte 30 \
    --export_dir /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output \
    --filter exercise_price:4200 \
    --template

2025-04-09 18:52:39,560 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-04-09 18:52:39,565 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'OESX'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250409), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=OESX&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250409&live_timestamp=0&live=True
Request successful.
Filtered down to 12 items.
Series exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output
Template exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output

In [2]:
!margin_estimator_tool get_series \
    --version LIVE \
    --products OESX \
    --min_tte 30 \
    --export_dir /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool \
    --filter exercise_price:4200 \
    --template

2025-04-09 18:52:31,086 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-04-09 18:52:31,091 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'OESX'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250409), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=OESX&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250409&live_timestamp=0&live=True
Request successful.
Filtered down to 66 items.
Series exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool
Template exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool

Now we have our options filtered down. Let's see how the templates look like:

In [4]:
with open("../output/20250409_LIVE_etd_portfolio_template.csv", "r") as f:
    print(f.read())

Product ID,Contract Date,Call Put Flag,Exercise Price,Version Number,Net LS Balance
OESX,20250417,C,4200.0,0,
OESX,20250417,P,4200.0,0,
OESX,20250411,P,4200.0,0,
OESX,20250425,C,4200.0,0,
OESX,20250425,P,4200.0,0,
OESX,20250411,C,4200.0,0,
OESX,20250502,C,4200.0,0,
OESX,20250430,C,4200.0,0,
OESX,20250502,P,4200.0,0,
OESX,20250509,C,4200.0,0,
OESX,20250509,P,4200.0,0,
OESX,20250430,P,4200.0,0,

In [5]:
with open("../20250409_LIVE_etd_portfolio_template.csv", "r") as f:
    print(f.read())

Product ID,Contract Date,Call Put Flag,Exercise Price,Version Number,Net LS Balance
OESX,20261218,C,4200.0,0,
OESX,20251219,P,4200.0,0,
OESX,20261218,P,4200.0,0,
OESX,20251219,C,4200.0,0,
OESX,20271217,P,4200.0,0,
OESX,20271217,C,4200.0,0,
OESX,20281215,P,4200.0,0,
OESX,20281215,C,4200.0,0,
OESX,20291221,C,4200.0,0,
OESX,20291221,P,4200.0,0,
...

For our purposes, picking only one option from each portfolio is sufficient. Let's create our portfolio now. We will take one short option that we will sell and one long option that we would buy. This is how our portfolio will look like after entering positions (we will sell 100 positions and similarly buy 100 positions):

In [1]:
with open("../output/20250409_LIVE_etd_portfolio_template.csv", "r") as f:
    print(f.read())

Product ID,Contract Date,Call Put Flag,Exercise Price,Version Number,Net LS Balance
OESX,20250417,C,4200.0,0,-100
OESX,20261218,C,4200.0,0,100

Now, let's send it to estimator endpoint to process the margins. We will export it to JSON.

In [3]:
!margin_estimator_tool etd_portfolio \
    --version LIVE \
    --csv_file ../output/20250409_LIVE_etd_portfolio_template.csv \
    --to_json \
    --export_dir /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output \
    --date 20250409

2025-04-19 19:05:20,499 api-client INFO   cpme_api configuration.enable_logging   Logger start.
Headers validated successfully.
2025-04-19 19:05:20,504 api-client INFO   cpme_api rest.POST             /estimator	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/estimator
Request successful.
Portfolio exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output

## Output Interpretation

Let's now analyze the output. We will first load the portfolio.

In [4]:
import json
import pandas as pd

with open('../output/20250409_LIVE_estimator.json', 'r') as file:
    data = json.load(file)

# Extract portfolio margin details
portfolio_margin = data["portfolio_margin"][0]

initial_margin = portfolio_margin['initial_margin']
market_risk = portfolio_margin['market_risk']
premium_margin = portfolio_margin['premium_margin']

# Display the portfolio margin summary
portfolio_margin_summary = {
    "Initial Margin": initial_margin,
    "Market Risk": market_risk,
    "Premium Margin": premium_margin,
}

portfolio_margin_summary_df = pd.DataFrame(portfolio_margin_summary, index=[0])
portfolio_margin_summary_df

   Initial Margin   Market Risk  Premium Margin
0    89577.833752  89541.117952       -195326.0

In [5]:
# Extract and display the drilldown data for each instrument
drilldown_data = data["drilldowns"]
drilldown_list = []

for d in drilldown_data:
    drilldown_list.append({
        "Product ID": d["product_id"],
        "Contract Date": d["contract_date"],
        "Type": "Call" if d["call_put_flag"] == "C" else "Put",
        "Exercise Price": d["exercise_price"],
        "Position": "Long" if d["net_ls_balance"] > 0 else "Short",
        "Component Margin": d["component_margin"],
        "Premium Margin": d["premium_margin"]
    })

drilldown_df = pd.DataFrame(drilldown_list)
drilldown_df

,Product ID,Contract Date,Type,Exercise Price,Position,Component Margin,Premium Margin
0,OESX,20261218,Call,4200.0,Long,-217895.680409,-775575.0
1,OESX,20250417,Call,4200.0,Short,307473.514161,580249.0

Now, let's see and compare how would the margins looks like if we only sold the short option.
We will change our portfolio accordingly:

In [7]:
with open("../output/20250409_LIVE_etd_portfolio_template.csv", "r") as f:
    print(f.read())

Product ID,Contract Date,Call Put Flag,Exercise Price,Version Number,Net LS Balance
OESX,20250417,C,4200.0,0,-100

And now we will run the same calculation again:

In [8]:
!margin_estimator_tool etd_portfolio \
    --version LIVE \
    --csv_file ../output/20250409_LIVE_etd_portfolio_template.csv \
    --to_json \
    --export_dir /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output \
    --date 20250409

2025-04-19 19:11:19,772 api-client INFO   cpme_api configuration.enable_logging   Logger start.
Headers validated successfully.
2025-04-19 19:11:19,777 api-client INFO   cpme_api rest.POST             /estimator	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/estimator
Request successful.
Portfolio exported to /home/gk101/workspace/DAVe-MarginEstimator-PythonAPIClient/margin_estimator_tool/output

In [9]:
with open('../output/20250409_LIVE_estimator.json', 'r') as file:
    data = json.load(file)

portfolio_margin = data["portfolio_margin"][0]

initial_margin = portfolio_margin['initial_margin']
market_risk = portfolio_margin['market_risk']
premium_margin = portfolio_margin['premium_margin']

portfolio_margin_summary = {
    "Initial Margin": initial_margin,
    "Market Risk": market_risk,
    "Premium Margin": premium_margin,
}

portfolio_margin_summary_df = pd.DataFrame(portfolio_margin_summary, index=[0])
portfolio_margin_summary_df

   Initial Margin    Market Risk  Premium Margin
0   306570.662207  306513.177041        580249.0

In [10]:
drilldown_data = data["drilldowns"]
drilldown_list = []

for d in drilldown_data:
    drilldown_list.append({
        "Product ID": d["product_id"],
        "Contract Date": d["contract_date"],
        "Type": "Call" if d["call_put_flag"] == "C" else "Put",
        "Exercise Price": d["exercise_price"],
        "Position": "Long" if d["net_ls_balance"] > 0 else "Short",
        "Component Margin": d["component_margin"],
        "Premium Margin": d["premium_margin"]
    })

drilldown_df = pd.DataFrame(drilldown_list)
drilldown_df

,Product ID,Contract Date,Type,Exercise Price,Position,Component Margin,Premium Margin
0,OESX,20250417,Call,4200.0,Short,306570.662207,580249.0

We can see that the margins are way higher now. This is due to lack of long option, which acted as hedging.
We can also experiment with different values for `min_tte` and `max_tte`, as well as different values for exercise price and position size. These values can have impact on margin, and it is up to the trader to find the right balance to minimize the margins or try to maximize profit.

## Conclusion

In a calendar spread, the margin analysis highlights the effects of the short-term sold option and the long-term bought option. The negative margin for the long-term option is offsetting the margin requirement for the short-term option, reducing the overall margin for the entire calendar spread. 

This structure of the portfolio helps manage risk and capital efficiency, with the premium margin indicating the income from selling the short-term option. The net margin reflects the hedged nature of the position, with an overall reduced margin requirement compared to outright options trades.