# Margin Estimator Tool Tutorial: Using the `get_series` Feature

This tutorial demonstrates how to use the `get_series` command from the margin estimator tool to fetch and filter series data. We'll explore various parameters and options to help us effectively use this feature.

## Introduction

The `get_series` command allows us to fetch financial instrument series data for specific products from the series endpoint. It supports:

- Filtering by type (option/future), call/put flag
- Filtering by time to expiration (TTE)
- Specifying product(s) (mandatory)
- Specifying business date (defaults to current date in YYYYMMDD form), version (LIVE or EOD), and timestamp for LIVE version
- Generating ETD portfolio templates
- Export to Excel, JSON, or  (default) CSV formats. Excel and JSON are mutually exclusive
- Apply custom filters using key-value pairs

Let's now check options vailable to us:

In [2]:
# Display help
!margin_estimator_tool get_series --help

Usage: margin_estimator_tool get_series [OPTIONS]

  Fetch series from the series endpoint.

Options:
  --date TEXT             Fetch products from a specific date (YYYYMMDD).
  --version [EOD|LIVE]    Fetch products based on version.
  --timestamp INTEGER     This defines the timestamp for the series data.
  --to_excel              Export as Excel file.
  --to_json               Export as JSON file.
  --export_dir PATH       Directory to save output.
  --products TEXT         Allows filtering series by product names.
                          [required]
  --type [option|future]  Filters the series based on type.
  --call_put_flag [C|P]   Filters the series based on call/put.
  --template              Generate template for ETD portfolio.
  --max_tte INTEGER       Filters based on the days_to_expiration (time to
                          expiry).
  --min_tte INTEGER       Filters based on the days_to_expiration (time to
                          expiry).
  --filter TEXT           Filter series based on key:value pairs separated by comma. The extrafields with examples are:
                          iid: 78490800
                          product_id: BMW
                          contract_date: 20250321
                          contract_maturity: 202503
                          expiry_maturity: 202503
                          version_number: 0
                          act_trade_unit_no: 100.0
                          days_to_expiration: 50
                          trade_unit_value: 100.0
                          contract_frequency: MONTHLY
                          call_put_flag: P
                          exercise_price: 91.0
                          exercise_style_flag: A
  --help                  Show this message and exit.

## Basic Usage for the Current Day

Let's start with a basic example of fetching series data for a specific product. We need to use the version LIVE, if the request for today's date should be successful.

In [48]:
# Basic usage - fetch series data for BMW product
!margin_estimator_tool get_series \
    --products BMW \
    --version LIVE

2025-03-06 15:25:42,112 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:25:42,119 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 1105 items.
Series exported to /project root directory/

This command fetches all series data for the BMW product, and exports it as a CSV file to the default directory. By default, without specifying `--to_excel` or `--to_json`, the data is exported as CSV.

## Sample Output

Here's what the exported CSV might look like:

In [49]:
# Display the output file (this is just for demonstration)
import pandas as pd
pd.read_csv("/path to file/").head(3)

,iid,product_id,contract_date,contract_maturity,expiry_maturity,version_number,act_trade_unit_no,days_to_expiration,trade_unit_value,contract_frequency,call_put_flag,exercise_price,exercise_style_flag
0,42743588,BMW,20251219,202512,202512,0,100.0,289,100.0,MONTHLY,C,52.0,A
1,42743771,BMW,20251219,202512,202512,0,100.0,289,100.0,MONTHLY,P,60.0,A
2,42743796,BMW,20251219,202512,202512,0,100.0,289,100.0,MONTHLY,P,68.0,A

## Fetching multiple Products with Historic Date

You can fetch series data for multiple products by separating them with commas.
Let's also use the historic date in YYYYMMDD format, but we need to keep in mind that this kind of request may take up to 5 minutes to complete.

In [50]:
# Fetch series for multiple products and historic request
!margin_estimator_tool get_series \
    --products BMW,DAI \
    --date 20250228

2025-03-06 15:25:56,335 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:25:56,340 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('products', 'DAI'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250228), ('live_timestamp', 0), ('live', False)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&products=DAI&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250228&live_timestamp=0&live=False
Request successful.
Filtered down to 1982 items.
Series exported to /project root directory/

## Filtering by Series Type (Option/Future)

You can filter series data by type using the `--type` parameter:

In [53]:
# Filter by type (option) and call_put_flag (C)
!margin_estimator_tool get_series \
    --products BMW \
    --type option \
    --version LIVE

2025-03-06 15:26:55,819 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:26:55,824 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 1105 items.
Series exported to /project root directory/

In [52]:
# Filter by type (future)
!margin_estimator_tool get_series \
    --products BMW \
    --type future \
    --version LIVE

2025-03-06 15:26:06,165 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:26:06,169 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 0 items.
No data found.

## Filtering by Call/Put Flag

For option series, you can filter by call or put flag:

In [55]:
# Filter by call flag
!margin_estimator_tool get_series \
    --products BMW \
    --call_put_flag C \
    --version LIVE

2025-03-06 15:27:29,655 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:27:29,662 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 556 items.
Series exported to /project root directory/

In [57]:
# Filter by put flag
!margin_estimator_tool get_series \
    --products BMW \
    --call_put_flag P \
    --version LIVE

2025-03-06 15:27:42,398 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:27:42,403 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 549 items.
Series exported to /project root directory/

## Filtering by Time to Expiration (TTE)

You can filter series by their days to expiration using `--min_tte` and `--max_tte` parameters. Here, we will define the interval, but we can also choose only one of the filters:

In [58]:
# Filter by time to expiration (short-term options only)
!margin_estimator_tool get_series \
    --products BMW \
    --max_tte 30 \
    --min_tte 10 \
    --version LIVE

2025-03-06 15:27:49,862 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:27:49,866 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 257 items.
Series exported to /project root directory/

## Using Custom Filters

You can apply more specific filters using the `--filter` parameter with key-value pairs:

In [2]:
# Filter by specific exercise price
!margin_estimator_tool get_series \
    --products BMW \
    --filter "exercise_price:91" \
    --version LIVE

2025-03-07 11:07:08,314 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-07 11:07:08,319 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250307), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250307&live_timestamp=0&live=True
Request successful.
Filtered down to 16 items.
Series exported to /project root directory/

In [60]:
# Multiple filters combined with comma
!margin_estimator_tool get_series \
    --products BMW \
    --filter "exercise_price:91,call_put_flag:P,contract_date:20240315" \
    --version LIVE

2025-03-06 15:27:59,096 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:27:59,100 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 0 items.
No data found.

In this case, there were no series found with such filters.

## Exporting to Different Formats

You can export the data to Excel or JSON formats:

In [61]:
# Export to Excel
!margin_estimator_tool get_series \
    --products BMW \
    --to_excel \
    --version LIVE

2025-03-06 15:28:33,127 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:28:33,132 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 1105 items.
Series exported to /project root directory/

In [62]:
# Export to JSON
!margin_estimator_tool get_series \
    --products BMW \
    --to_json \
    --version LIVE

2025-03-06 15:28:38,477 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:28:38,482 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 1105 items.
Series exported to /project root directory/

## Generating an ETD Portfolio Template

You can generate a template for an ETD portfolio based on the filtered series:

In [64]:
# Generate a template for an ETD portfolio
!margin_estimator_tool get_series \
    --products BMW \
    --filter "exercise_price:91" \
    --template \
    --version LIVE

2025-03-06 15:28:50,035 api-client INFO   cpme_api configuration.enable_logging   Logger start.
2025-03-06 15:28:50,040 api-client INFO   cpme_api rest.GET              /series	HEADER:{'Content-Type': 'application/json', 'X-DBP-APIKEY': '9c40a29c-?..', 'User-Agent': 'cpME-api/3.0.0/python'} PARAMS:[('products', 'BMW'), ('extrafields', 'product_id,contract_date,contract_maturity,expiry_maturity,call_put_flag,exercise_price,version_number,iid,act_trade_unit_no,days_to_expiration,trade_unit_value,exercise_style_flag,contract_frequency'), ('business_date', 20250306), ('live_timestamp', 0), ('live', True)] URL:https://risk.developer.deutsche-boerse.com/prisma-margin-estimator-2-0-0/series?products=BMW&extrafields=product_id%2Ccontract_date%2Ccontract_maturity%2Cexpiry_maturity%2Ccall_put_flag%2Cexercise_price%2Cversion_number%2Ciid%2Cact_trade_unit_no%2Cdays_to_expiration%2Ctrade_unit_value%2Cexercise_style_flag%2Ccontract_frequency&business_date=20250306&live_timestamp=0&live=True
Request successful.
Filtered down to 16 items.
Series exported to /project root directory/
Template exported to /project root directory/

The generated template will look like this:

In [65]:
# Display the template (for demonstration)
pd.read_csv("/path to template/").head(3)

,Product ID,Contract Date,Call Put Flag,Exercise Price,Version Number,Net LS Balance
0,BMW,20250321,C,91.0,0,NaN
1,BMW,20250417,C,91.0,0,NaN
2,BMW,20250417,P,91.0,0,NaN

The user will manually need to enter positions into Net LS Balance, otherwise it will default to 0.

## Error Handling

The tool provides error messages for various scenarios:

In [66]:
# Error when using an invalid filter field
!margin_estimator_tool get_series \
    --products BMW \
    --filter "unknown_field:value" \
    --version LIVE

2025-03-06 15:28:58,636 api-client INFO   cpme_api configuration.enable_logging   Logger start.
Error: Invalid filter key: unknown_field. Must be one of {'expiry_maturity', 'contract_maturity', 'product_id', 'iid', 'exercise_price', 'days_to_expiration', 'contract_frequency', 'contract_date', 'call_put_flag', 'act_trade_unit_no', 'exercise_style_flag', 'trade_unit_value', 'version_number'}

In [3]:
# Error for invalid numeric value
!margin_estimator_tool get_series \
    --products BMW \
    --filter "exercise_price:string_value" \
    --version LIVE

2025-03-07 11:10:17,972 api-client INFO   cpme_api configuration.enable_logging   Logger start.
Error: Invalid integer value for exercise_price: string_value

## Understanding the Series Data

Here's an explanation of the key fields in the series data:

| Field | Description |
|-------|-------------|
| `product_id` | Identifier for the financial product (e.g., BMW) |
| `contract_date` | Date of the contract expiration (YYYYMMDD) |
| `call_put_flag` | 'C' for call options, 'P' for put options, null for futures |
| `exercise_price` | Strike price for options |
| `version_number` | Version of the contract |
| `iid` | Unique identifier for the instrument |
| `act_trade_unit_no` | Number of units in a standard trade |
| `days_to_expiration` | Days remaining until contract expiration |
| `contract_maturity` | Contract maturity month and year (YYYYMM) |
| `expiry_maturity` | Expiration maturity month and year (YYYYMM) |
| `trade_unit_value` | Value per trade unit |
| `exercise_style_flag` | 'A' for American, 'E' for European style options |
| `contract_frequency` | Frequency of the contract (e.g., MONTHLY) |

## Summary

The `get_series` command is a tool for fetching and filtering financial instrument series data. By combining various parameters, we can precisely select the data we need and export it in our preferred format.

This data can be used for further analysis or as input to other components of the margin estimator tool, such as the margin calculator.

Remember to check the documentation or use the `--help` option for detailed information about all available parameters.